import Head from 'next/head'
import { Inter } from '@next/font/google'
import Slider from '../component/slider'
import ResponsiveFormModal from '../component/modal'
import Navbar from '../component/navbar'
// import styles from '@/styles/Home.module.css'
// import CompleteForm from '@/component/form'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   {/* <h2>Hello from Home</h2> */}
   <Navbar />
   <ResponsiveFormModal />
   <Slider />
  
   {/* <CompleteForm /> */}
   {/* <Hell /> */}
   {/* <Link href="/form"><button>Form</button></Link> */}
    </>
  )
}
